# Generated by Django 4.2.5 on 2023-09-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_alter_tag_options_remove_tag_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
