# Generated by Django 4.2.5 on 2023-09-07 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='scopes',
            field=models.ManyToManyField(related_name='tags', through='articles.Scope', to='articles.article', verbose_name='Категории'),
        ),
    ]
