# Generated by Django 4.1.7 on 2023-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
