# примеры API-запросов

@baseUrl = http://localhost:8005/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "DS18B20",
  "description": "Датчик в подъезде"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/4/
Content-Type: application/json

{
  "description": "Перенес датчик в коредор"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 15.0
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/2/
Content-Type: application/json

###

# получение информации по измерениям
GET {{baseUrl}}/measurements/
Content-Type: application/json
